### ISSUE TITLE
getting error when compiling

### ISSUE THREAD

**Issue by prabhunath111** [JeffG05/emoji_picker#14]
.java:16: error: cannot find symbol
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
                                  ^
  symbol:   class NonNull
  location: class EmojiPickerPlugin
C:\Users\prabhunath\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.0.3\android\src\main\java\com\jeffg\emoji_picker\EmojiPickerPlugin.java:42: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                            ^
  symbol:   class NonNull
  location: class EmojiPickerPlugin
C:\Users\prabhunath\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.0.3\android\src\main\java\com\jeffg\emoji_picker\EmojiPickerPlugin.java:42: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                                                      ^
  symbol:   class NonNull
  location: class EmojiPickerPlugin
C:\Users\prabhunath\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.0.3\android\src\main\java\com\jeffg\emoji_picker\EmojiPickerPlugin.java:52: error: cannot find symbol
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
                                    ^
  symbol:   class NonNull
  location: class EmojiPickerPlugin
C:\Users\prabhunath\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.0.3\android\src\main\java\com\jeffg\emoji_picker\EmojiPickerPlugin.java:17: error: cannot access LifecycleOwner
    final MethodChannel channel = new MethodChannel(flutterPluginBinding.getFlutterEngine().getDartExecutor(),
                                                                        ^
  class file for androidx.lifecycle.LifecycleOwner not found
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':emoji_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by prabhunath111** [comment]
After the update my SDK it's working, Can anyone do clear how to hide emoji pop up?

**Comment by ken-ng-esotec** [comment]
@prabhunath111 , what did you update to get this working? You said SDK but I don't understand - could you please clarify. 🙏 thank you
