### ISSUE TITLE
List of emoji reloads everytime the it's opened. made a suggestion

### ISSUE THREAD

**Issue by jpainam** [JeffG05/emoji_picker#20]
Hi, The first time the user open the emoji, a time is spent and a loading widget is shown before displaying the list of emojis. This repeats everytime the user opens the emoji. You can use `AutomaticKeepAliveClientMixin` with 
```dart
 @override
  bool get wantKeepAlive => true;
```
to keep the state of the emoji widget alive after the first reload.

Nice library by the way

**Comment by deep1931** [comment]
Hi,
I have added AutomaticKeepAliveClientMixin and called super.build in build method. But still same,  loading emojis every time and take some time to load.  

Please help

**Comment by blisssan** [comment]
> Hi,
> I have added AutomaticKeepAliveClientMixin and called super.build in build method. But still same, loading emojis every time and take some time to load.
> 
> Please help

I have made a PR for improving load times & caching previously filtered emojis to Preferences. It has greatly improved for me. Its not yet approved by the maintainer so if needed clone my fork https://github.com/blisssan/emoji_picker and use it in your pubspec like this 

```
emoji_picker:
    path: 'cloned/repo/directory/path'
```

**Comment by deep1931** [comment]
Thanks for the update.

**Comment by jpainam** [comment]
Going to close this repo. as @blisssan  suggested. you can use his fork.
