### ISSUE TITLE
Scroll Performance extremly slow

### ISSUE THREAD

**Issue by Ahmadre** [JeffG05/emoji_picker#4]
Hey Jeff :),

I recognized a really bad performance in scrolling between pages in your PageView implementation. 

It was because of NeverScrollableScrollPhysics. Not the yellow of the egg by flutter.

Just change it to: 

```dart
physics: AlwaysScrollableScrollPhysics(),
```

and you should've removed that performance issue.

Greetings
Rebar

**Comment by JeffG05** [comment]
Thanks! This issue should now be solved.

**Comment by kennethlzh2** [comment]
Hi this issue still exist, its very slow when scrolling

**Comment by Mohamed-Fakhry** [comment]
This issue still exist, its very slow when scrolling

**Comment by tomwyr** [comment]
The `build` method of `EmojiPicker` is huge, like 1200 lines of code or so. You probably do a lot of unnecessary stuff inside it which is executed on each scroll update.
