### ISSUE TITLE
Some emoji did not convert successfully

### ISSUE THREAD

**Issue by webphplove** [JeffG05/emoji_picker#5]
My Android phone has a lot of expressions that have not been converted successfully, like the picture below.
![Image of Yaktocat](http://ppb88rr1p.bkt.clouddn.com/S90425-172340.png?imageView2/2/w/608/h/610/interlace/1/q/100)

This is my real machine test. How to solve this?

**Comment by JeffG05** [comment]
This is due to unicode characters not being supported on all devices. Currently there is no solution but I am looking into it

**Comment by webphplove** [comment]
ok, think you!
