### ISSUE TITLE
Many missing emojis shows cross/question icon on Android/iOS (plus one more weird problem)

### ISSUE THREAD

**Issue by sgon00** [JeffG05/emoji_picker#6]
First, thanks a lot for the package.
I just run the example code provided in the github repo.
Please, check the following screenshots:

![emoji1](https://user-images.githubusercontent.com/1555508/57198055-18eb4380-6fa1-11e9-9605-1d2b7170cb0a.jpg)
![emoji2](https://user-images.githubusercontent.com/1555508/57198063-21dc1500-6fa1-11e9-999a-efc84a9872e2.jpg)
![emoji3](https://user-images.githubusercontent.com/1555508/57198065-27d1f600-6fa1-11e9-8730-a920d75dc6f1.jpg)

The above screenshots from physical android device. I tried the same on iOS emulator. It gave me the same/similar result, please check the iOS screenshot:

<img width="425" alt="Screen Shot 2019-05-06 at 01 54 50" src="https://user-images.githubusercontent.com/1555508/57198174-5ef4d700-6fa2-11e9-833a-e30959b12608.png">

**Btw, One more weird issue**, when I press the keyboard `S` in the `flutter run` console to take a screenshot, the activated tab is auto changed to the first tab. (but the activating emoji window doesn't change). I have no ideas why a keyboard press in the console will make a different in the UI. To see what I mean, check the following screenshot:

<img width="1068" alt="Screen Shot 2019-05-06 at 01 55 28" src="https://user-images.githubusercontent.com/1555508/57198184-78961e80-6fa2-11e9-9b0f-e2f751816137.png">

**Comment by darasat** [comment]
Good day!

Did this issue was solved?

I have the same behaviour.. with non show some kind of emojis on android emulator..
