### ISSUE TITLE
Changing the recommended icon

### ISSUE THREAD

**Issue by jimmyff** [JeffG05/emoji_picker#9]
Hey, great plugin! The performance seems a bit slow on my Pixel 3 but I'm guessing thats just because I'm running in debug mode.

The recommended icon is currently a search magnifying glass, I think this is a little confusing as I would expect hitting the search to allow me to search for an emoji. Is it possible to allow us to override the Recommended icon to something else? Would be great just to accept `IconData`. Also it would be nice to provide a `Color` which is used for the pagination tint?

Thanks

**Comment by JeffG05** [comment]
Hi,

Updating the icons and pagination indicator is already available. I will update the README to make this a bit clearer!

```
EmojiPicker(
  categoryIcons: CategoryIcons(
    recommendationIcon: CategoryIcon(icon: Icons.search) // replace 'Icons.search' with an icon of your choice
  ),
  indicatorColor: Colors.red // replace 'Colors.red' with a color of your choice
)
```

Hope this helps!
